apiVersion: skaffold/v2alpha4
kind: Config
build:
  artifacts:
    - image: kubesail/agent
      context: .
      sync:
        manual:
          - src: lib/**/*
            dest: /app/lib/
            strip: lib/
      docker:
        dockerfile: Dockerfile
    - image: kubesail/gateway
      context: .
      sync:
        manual:
          - src: lib/**/*
            dest: /app/lib/
            strip: lib/
      docker:
        dockerfile: Dockerfile
    - image: kubesail/test-endpoint
      context: .
      sync:
        manual:
          - src: lib/**/*
            dest: /app/lib/
            strip: lib/
      docker:
        dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
      - k8s/overlays/dev
