---
apiVersion: v1
kind: Service
metadata:
  name: kubesail-gateway-metrics
spec:
  ports:
    - name: metrics
      port: 5000
      protocol: TCP
      targetPort: metrics
  selector:
    app: kubesail-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: kubesail-agent-metrics
spec:
  ports:
    - name: metrics
      port: 5000
      protocol: TCP
      targetPort: metrics
  selector:
    app: kubesail-agent
