apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubesail-agent
spec:
  selector:
    matchLabels:
      app: kubesail-agent
  minReadySeconds: 1
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/port: "5000"
        prometheus.io/scrape: "true"
      labels:
        app: kubesail-agent
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: kubesail-agent
          image: kubesail/agent:latest
          imagePullPolicy: Never
          command: ["/app/bin/kubesail-agent"]
          ports:
            - name: metrics
              containerPort: 5000
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: LOG_LEVEL
              value: debug
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: "2"
              memory: 1500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kubesail-agent
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
    - name: metrics
      port: 5000
      protocol: TCP
      targetPort: metrics
  selector:
    app: kubesail-agent
