bases:
  - ../../../agent
patchesStrategicMerge:
  - ./agent.yaml
secretGenerator:
  - name: agent
    envs:
      - secrets/env.plain
  - name: self-signed
    files:
      - tls.crt=secrets/tls.crt
      - tls.key=secrets/tls.key
    type: 'kubernetes.io/tls'
