apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubesail-agent
spec:
  template:
    spec:
      containers:
        - name: kubesail-agent-test
          image: kubesail/test:latest
          imagePullPolicy: Never
          command: ["/app/bin/test-agent"]
          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: LOG_LEVEL
              value: debug
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: "2"
              memory: 1500Mi
