apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubesail-gateway
spec:
  template:
    spec:
      containers:
        # - name: kubesail-gateway-test
        #   image: kubesail/test:latest
        #   imagePullPolicy: Never
        #   command: ["/app/bin/test-gateway"]
        #   env:
        #     - name: GET_HOSTS_FROM
        #       value: dns
        #     - name: LOG_LEVEL
        #       value: debug
        #     - name: NODE_ENV
        #       value: development
        #   resources:
        #     requests:
        #       cpu: 50m
        #       memory: 100Mi
        #     limits:
        #       cpu: "2"
        #       memory: 1500Mi
        - name: kubesail-gateway
          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: LOG_LEVEL
              value: debug
            - name: NODE_ENV
              value: development
            - name: APP_ENV
              value: dev
            - name: KUBESAIL_API_TARGET
              value: api
