bases:
  - ../../agent
  - ../../gateway
  - ../../test-endpoint
resources:
  - ./nginx-service.yaml
  - ./nginx-ingress.yaml
  - ./redis.yaml
patchesStrategicMerge:
  - ./patches/agent.yaml
  - ./patches/gateway.yaml
secretGenerator:
  - name: self-signed
    files:
      - tls.crt=secrets/tls.crt.pem
      - tls.key=secrets/tls.key.pem
    type: "kubernetes.io/tls"
  - name: agent
    envs:
      - secrets/env.plain
